packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  supabase: true
  sharp: true
  unrs-resolver: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@anthropic-ai/sdk@0.104.2'
